using UnityEngine;
using UnityEditor;
using System.Diagnostics;
using System.IO;
using System.Threading.Tasks;
using System.Linq;
using System.Collections.Generic;

public class VideoChartGeneratorWindow : EditorWindow
{
    private enum SourceType { YouTubeUrl, LocalVideo }
    
    private SourceType sourceType = SourceType.YouTubeUrl;
    private string youtubeUrl = "";
    private string localVideoPath = "";
    private string outputFolderName = "AutoGenerated";
    
    private bool showVisuals = true;
    private bool saveDebugVideo = false;
    
    private float minNoteInterval = 0.5f;
    private float minWallInterval = 1.5f;
    
    private bool mergeMode = false;
    private string targetChartFolder = "AutoGenerated";
    private float mergeStartTime = 0.0f;
    private float mergeEndTime = 30.0f;
    private bool extractOnlyLongNotes = true;
    
    private bool isProcessing = false;
    private string statusMessage = "Ready.";

    [MenuItem("Chart/Video Chart Generator")]
    public static void ShowWindow()
    {
        GetWindow<VideoChartGeneratorWindow>("Video Chart Gen");
    }

    private void OnGUI()
    {
        GUILayout.Label("Dance Video -> Chart Generator", EditorStyles.boldLabel);
        EditorGUILayout.Space();

        string toolsDir = Path.Combine(Application.dataPath, "../Tools/AutoChartGenerator");
        string venvPython = Path.Combine(toolsDir, "venv/Scripts/python.exe");
        
        bool isSetup = File.Exists(venvPython);
        
        if (!isSetup)
        {
            EditorGUILayout.HelpBox("Python environment is not set up yet.\nPlease click the button below to install dependencies.", MessageType.Warning);
            if (GUILayout.Button("Setup Python Environment (Runs setup_and_run.bat)", GUILayout.Height(30)))
            {
                RunSetupBat(toolsDir);
            }
            return;
        }

        sourceType = (SourceType)EditorGUILayout.EnumPopup("Source Type", sourceType);

        if (sourceType == SourceType.YouTubeUrl)
        {
            youtubeUrl = EditorGUILayout.TextField("YouTube URL", youtubeUrl);
        }
        else
        {
            EditorGUILayout.BeginHorizontal();
            localVideoPath = EditorGUILayout.TextField("Local Video (.mp4)", localVideoPath);
            if (GUILayout.Button("Browse", GUILayout.Width(70)))
            {
                string path = EditorUtility.OpenFilePanel("Select Dance Video", "", "mp4,mkv,avi");
                if (!string.IsNullOrEmpty(path))
                    localVideoPath = path;
            }
            EditorGUILayout.EndHorizontal();
        }

        EditorGUILayout.Space();
        outputFolderName = EditorGUILayout.TextField("Output Folder Name", outputFolderName);

        EditorGUILayout.Space();
        GUILayout.Label("Merge Options", EditorStyles.boldLabel);
        mergeMode = EditorGUILayout.Toggle("Merge with Existing Chart", mergeMode);
        if (mergeMode)
        {
            targetChartFolder = EditorGUILayout.TextField("Target Chart Folder", targetChartFolder);
            mergeStartTime = EditorGUILayout.FloatField("Merge Start Time (s)", mergeStartTime);
            mergeEndTime = EditorGUILayout.FloatField("Merge End Time (s)", mergeEndTime);
            extractOnlyLongNotes = EditorGUILayout.Toggle("Extract Only Long Notes", extractOnlyLongNotes);
        }

        EditorGUILayout.Space();
        GUILayout.Label("Options", EditorStyles.boldLabel);
        
        minNoteInterval = EditorGUILayout.Slider("Min Note Interval (s)", minNoteInterval, 0.1f, 2.0f);
        minWallInterval = EditorGUILayout.Slider("Min Wall Interval (s)", minWallInterval, 0.5f, 5.0f);
        
        showVisuals = EditorGUILayout.Toggle("Show Realtime Visuals", showVisuals);
        saveDebugVideo = EditorGUILayout.Toggle("Save Debug Video", saveDebugVideo);

        EditorGUILayout.Space();

        GUI.enabled = !isProcessing;
        if (GUILayout.Button(isProcessing ? "Processing... (Please Wait)" : "Generate Chart!", GUILayout.Height(40)))
        {
            RunGenerator(toolsDir, venvPython);
        }
        GUI.enabled = true;

        EditorGUILayout.Space();
        EditorGUILayout.LabelField("Status:", statusMessage, EditorStyles.wordWrappedLabel);
    }

    private void RunSetupBat(string toolsDir)
    {
        string batPath = Path.Combine(toolsDir, "setup_and_run.bat");
        if (!File.Exists(batPath))
        {
            EditorUtility.DisplayDialog("Error", "setup_and_run.bat not found!", "OK");
            return;
        }

        ProcessStartInfo psi = new ProcessStartInfo
        {
            FileName = batPath,
            WorkingDirectory = toolsDir,
            UseShellExecute = true
        };
        Process.Start(psi);
        statusMessage = "Running setup. Please restart this window after setup finishes.";
    }

    private async void RunGenerator(string toolsDir, string pythonPath)
    {
        if (sourceType == SourceType.YouTubeUrl && string.IsNullOrWhiteSpace(youtubeUrl))
        {
            EditorUtility.DisplayDialog("Error", "Please enter a YouTube URL.", "OK");
            return;
        }
        if (sourceType == SourceType.LocalVideo && string.IsNullOrWhiteSpace(localVideoPath))
        {
            EditorUtility.DisplayDialog("Error", "Please select a local video.", "OK");
            return;
        }

        isProcessing = true;
        statusMessage = "Running AI Pose Tracking... Please don't close Unity.";
        Repaint();

        string generatorScript = Path.Combine(toolsDir, "generator.py");
        string outDir = Path.Combine(Application.streamingAssetsPath, "Charts", outputFolderName).Replace("\\", "/");
        string args = $"\"{generatorScript}\" --outdir \"{outDir}\"";
        
        if (sourceType == SourceType.YouTubeUrl)
            args += $" --url \"{youtubeUrl}\"";
        else
            args += $" --video \"{localVideoPath}\"";

        if (!showVisuals) args += " --novisual";
        if (saveDebugVideo) args += " --savevideo";
        args += $" --min_interval {minNoteInterval} --wall_interval {minWallInterval}";

        await Task.Run(() =>
        {
            ProcessStartInfo psi = new ProcessStartInfo
            {
                FileName = "cmd.exe",
                Arguments = $"/k \"\"{pythonPath}\" {args} & exit\"",
                WorkingDirectory = toolsDir,
                UseShellExecute = true,
                CreateNoWindow = false
            };

            try
            {
                using (Process process = Process.Start(psi))
                {
                    process.WaitForExit();
                }
            }
            catch (System.Exception e)
            {
                UnityEngine.Debug.LogError("Error running Python generator: " + e.Message);
            }
        });

        if (mergeMode)
        {
            try
            {
                string generatedPath = Path.Combine(outDir, "chart.json");
                string targetDir = Path.Combine(Application.streamingAssetsPath, "Charts", targetChartFolder).Replace("\\", "/");
                string targetPath = Path.Combine(targetDir, "chart.json");

                if (File.Exists(generatedPath) && File.Exists(targetPath))
                {
                    string genJson = File.ReadAllText(generatedPath);
                    string targetJson = File.ReadAllText(targetPath);

                    ChartData genChart = JsonUtility.FromJson<ChartData>(genJson);
                    ChartData targetChart = JsonUtility.FromJson<ChartData>(targetJson);

                    targetChart.notes.RemoveAll(n => n.time >= mergeStartTime && n.time <= mergeEndTime);

                    IEnumerable<NoteInfo> newNotes = genChart.notes.Where(n => n.time >= mergeStartTime && n.time <= mergeEndTime);
                    if (extractOnlyLongNotes)
                    {
                        newNotes = newNotes.Where(n => n.duration > 0);
                    }

                    targetChart.notes.AddRange(newNotes);
                    targetChart.notes.Sort((a, b) => a.time.CompareTo(b.time));

                    File.WriteAllText(targetPath, JsonUtility.ToJson(targetChart, true));
                    statusMessage = $"Merged into {targetChartFolder} successfully!";
                }
                else
                {
                    statusMessage = "Merge failed: chart.json not found.";
                }
            }
            catch (System.Exception e)
            {
                UnityEngine.Debug.LogError("Error during merge: " + e.Message);
                statusMessage = "Merge error!";
            }
        }
        else
        {
            statusMessage = $"Done! Chart generated at StreamingAssets/Charts/{outputFolderName}";
        }

        isProcessing = false;
        AssetDatabase.Refresh();
        Repaint();
        
        EditorUtility.DisplayDialog("Success", statusMessage, "Awesome!");
    }
}
